version: '2.2'
networks:
  got.jeppesensystems.com:
    driver: bridge
services:
  oracle:
    extends:
      file: ./docker-compose-base.yaml
      service: oracle
  xmlrpc:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc
  xmlrpc-vacation:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc-vacation
  xmlrpc-career:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc-career
  jboss:
    extends:
      file: ./docker-compose-base.yaml
      service: jboss
    depends_on:
      xmlrpc:
        condition: service_started
      xmlrpc-vacation:
        condition: service_started
      xmlrpc-career:
        condition: service_started
      oracle:
        condition: service_healthy
  healthcheck:
    extends:
      file: ./docker-compose-base.yaml
      service: healthcheck
    depends_on:
      xmlrpc:
        condition: service_started
      xmlrpc-vacation:
        condition: service_started
      xmlrpc-career:
        condition: service_started
      oracle:
        condition: service_healthy
      jboss:
        condition: service_healthy
