version: '2.2'
networks:
  got.jeppesensystems.com:
    driver: bridge
services:
  oracle:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/oracle
    hostname: crewportal-ora
    shm_size: 1g
    ports: ['1521:1521']
    networks:
      got.jeppesensystems.com:
        aliases:
          - crewportal-ora
          - crewportal-ora.got.jeppesensystems.com
    environment:
      APEX_PORT: 8080
    healthcheck:
      test: test `lsnrctl status | grep 'status READY' | wc -l` -eq 2 || exit -1
      interval: 5s
      timeout: 5s
      retries: 55
    # mem_limit: 1073741824 # container limit: 1024Mb (1024 * 1024 * 1024)
  xmlrpc:
    build:
      context: ../../
      dockerfile: ./dev/docker/xmlrpc/Dockerfile
    ports: ['24054:24054']
    networks: [got.jeppesensystems.com]
  xmlrpc-vacation:
    build:
      context: ../../
      dockerfile: ./dev/docker/xmlrpc/vacation/Dockerfile
    ports: ['24055:24055']
    networks: [got.jeppesensystems.com]
  xmlrpc-career:
    build:
      context: ../../
      dockerfile: ./dev/docker/xmlrpc/career/Dockerfile
    ports: ['24056:24056']
    networks: [got.jeppesensystems.com]
  jboss:
    build:
      context: ../../
      dockerfile: ./dev/docker/jboss/Dockerfile
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    healthcheck:
      test: curl http://127.0.0.1:8080/portal/
      interval: 6s
      timeout: 6s
      retries: 66
    networks: [got.jeppesensystems.com]
    # mem_limit: 1073741824 # container limit: 1024Mb (1024^3)
  healthcheck:
    image: alpine
    container_name: healthcheck
    command: >
      /bin/ash -c ' env ; \
                    echo "jboss app is ready for test" > /tmp/done ; \
                    tail -f /tmp/done ; '
    healthcheck:
      test: cat /tmp/done || exit 1
      interval: 7s
      timeout: 7s
      retries: 77
    networks: [got.jeppesensystems.com]
