version: '2.2'
networks:
  ymq.jeppesensystems.com:
    driver: bridge
services:
  hub:
    extends:
      file: ./docker-compose-base.yaml
      service: hub
  chrome:
    extends:
      file: ./docker-compose-base.yaml
      service: chrome
  firefox:
    extends:
      file: ./docker-compose-base.yaml
      service: firefox
  oracle:
    extends:
      file: ./docker-compose-base.yaml
      service: oracle
  jboss:
    extends:
      file: ./docker-compose-base.yaml
      service: jboss
    depends_on:
      oracle:
        condition: service_healthy
  xmlrpc:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc
  xmlrpc-vacation:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc-vacation
  xmlrpc-career:
    extends:
      file: ./docker-compose-base.yaml
      service: xmlrpc-career
  healthcheck:
    extends:
      file: ./docker-compose-base.yaml
      service: healthcheck
    depends_on:
      hub:
        condition: service_healthy
      oracle:
        condition: service_healthy
      jboss:
        condition: service_healthy
