# Pipeline to deploy latest test branch

trigger: none
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  major: $(Build.SourceBranchName)
  minor: $[counter(variables['Build.SourceBranchName'], 1)]

stages:
- template: templates/carmusr_deploy.yml
  parameters:
    carmsystemname: 'SASDEV'
    sasenv: 'CMS_Development'
    livefeed: true
- template: templates/carmusr_deploy.yml  # Template reference
  parameters:
    carmsystemname: 'PROD_TEST'
    sasenv: 'CMS_Prodtest'
    livefeed: true
