##########################################################
# Pipeline to build and deploy a feature branch to Dev and Test
# Will not move Livefeed (so it doesn't interfere with ordinary test release) and needs to be triggered manually
##########################################################

name: $(TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:r)

trigger: none

variables:
  major: $(Build.SourceBranchName)
  # Can't use $(Date) and $(Rev) outside of build number definition, so need to use format and counter instead
  runid: $[counter(format('{0}{1:yyyyMMdd}', variables['major'], pipeline.startTime), 1)]
  minor: $[format('{0:yyyyMMdd}_{1}', pipeline.startTime, variables['runid'])]

stages:
- template: templates/carmusr_build.yml
  parameters:
    publish: true

# Temporarily commenting out Dev stage since host cweudcmsin01 has issues
#- template: templates/carmusr_deploy.yml
#  parameters:
#    carmsystemname: 'SASDEV'
#    sasenv: 'CMS_Development'
#    livefeed: false

- template: templates/carmusr_deploy.yml
  parameters:
    carmsystemname: 'PROD_TEST'
    sasenv: 'CMS_Prodtest'
    livefeed: false
    summary: false
    
