trigger: none
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
variables:
- name: branch_name
  value: $(SourceBranchName)
schedules:
- cron: "0 19 * * *"
  displayName: Daily Behave test runs
  branches:
    include:
    - TestRelease/*
- cron: "0 12 * * 0"
  displayName: Weekly Sunday Tests on Prod branch
  branches:
    include:
    - ProdRelease/*
  always: true
jobs:
- template: templates/behavetests.yml
  parameters:
      buildId: $(Build.BuildId)
