##########################################################
# Pipeline to build and deploy latest TestRelease branch #
##########################################################

name: $(TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:r)

pr: none
schedules:
- cron: "0 14 * * *"
  displayName: 'Daily test release (Afternoon)'
  branches:
    include:
    - TestRelease/*
trigger: none

variables:
  major:  tracking_$(Build.SourceBranchName)
  # Can't use $(Date) and $(Rev) outside of build number definition, so need to use format and counter instead
  runid: $[counter(format('{0}{1:yyyyMMdd}', variables['major'], pipeline.startTime), 1)]
  minor: $[format('{0:yyyyMMdd}_{1}', pipeline.startTime, variables['runid'])]

stages:
- template: templates/carmusr_build.yml
  parameters:
    publish: true

# - template: templates/carmusr_deploy.yml
#   parameters:
#     carmsystemname: 'SASDEV'
#     sasenv: 'CMS_Development'
#     livefeed: true

- template: templates/carmusr_deploy.yml
  parameters:
    carmsystemname: 'PROD_TEST'
    sasenv: 'CMS_Prodtest'
    livefeed: true
    summary: true
    
