trigger: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: ValidateCommitTested
  pool:
    name: CMS Agent
      
  steps:
    - checkout: self

    - task: Bash@3
      inputs:
        filePath: 'bin/pipelines/validate_prod_commit.sh'
        arguments: '$(Build.SourceVersion) $(System.PullRequest.TargetBranch)'
        failOnStderr: true
      displayName: Find commit in test release branch
