version: '2.2'
networks:
  got.jeppesensystems.com:
    driver: bridge
services:
  oracle:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/oracle
    hostname: crewportal-ora
    shm_size: 1g
    ports: ['1521:1521']
    networks:
      got.jeppesensystems.com:
        aliases:
          - crewportal-ora
          - crewportal-ora.got.jeppesensystems.com
    environment:
      APEX_PORT: 8080
    healthcheck:
      test: test `lsnrctl status | grep 'status READY' | wc -l` -eq 2 || exit -1
      interval: 5s
      timeout: 5s
      retries: 55
  xmlrpc:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/xmlrpc-sas:10.1.6.0-SNAPSHOT
    hostname: xmlrpc-sas.got.jeppesensystems.com
    ports: ['24054:24054']
    networks: [got.jeppesensystems.com]
  xmlrpc-vacation:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/xmlrpc-vacation-sas:10.1.6.0-SNAPSHOT
    hostname: xmlrpc-vacation-sas.got.jeppesensystems.com
    ports: ['24055:24055']
    networks: [got.jeppesensystems.com]
  xmlrpc-career:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/xmlrpc-career-sas:10.1.6.0-SNAPSHOT
    hostname: xmlrpc-career-sas.got.jeppesensystems.com
    ports: ['24056:24056']
    networks: [got.jeppesensystems.com]
  jboss:
    image: docker.service.cloud.jeppesensystems.com/crew-buddies/ib6-sas/ib6-sas:10.1.6.0-SNAPSHOT
    hostname: ib6-sas.got.jeppesensystems.com
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    networks: [got.jeppesensystems.com]
  healthcheck:
    image: alpine
    container_name: healthcheck
    command: >
      /bin/ash -c ' env ; \
                    echo "jboss app is ready for test" > /tmp/done ; \
                    tail -f /tmp/done ; '
    healthcheck:
      test: cat /tmp/done || exit 1
      interval: 7s
      timeout: 7s
      retries: 77
    networks: [got.jeppesensystems.com]
